version: "2"

services:
    service-a:
        environment:
            - APPINSIGHTS_INSTRUMENTATIONKEY
        ports:
            - "80"
    
    service-b:
        environment:
            - APPINSIGHTS_INSTRUMENTATIONKEY
        expose:
            - "80"
