version: "2"
services:
    service-a:
        build: ./service-a
        image: service-a
        environment:
            - APPINSIGHTS_INSTRUMENTATIONKEY
        ports:
            - "8080:80"
        links:
            - service-b
    
    service-b:
        build: ./service-b
        image: service-b
        environment:
            - APPINSIGHTS_INSTRUMENTATIONKEY
        expose:
            - 80
