version: "2"

services:
    service-b-build:
        image: microsoft/dotnet
        volumes:
            - ./service-b:/src
        working_dir: /src
        command: /bin/bash -c "dotnet restore && dotnet publish -c Release -o bin ."
